name = "start-page"
main = "worker/index.js"
compatibility_date = "2024-12-01"

# To use a custom domain, uncomment and change:
# routes = [
#   { pattern = "yourdomain.com", custom_domain = true }
# ]

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[kv_namespaces]]
binding = "START_PAGE_DATA"
id = "YOUR_KV_NAMESPACE_ID"
